# Assemble and deploy to GitHub Pages.
#
# This using Jekyll to process Markdown to static HTML and JSDoc for the code.

name: Pages

on: push

env:
  REL_JK: jk
  ABS_JK: ${{ github.workspace }}/jk
  ABS_JSDOC: ${{ github.workspace }}/out
  API_README_MD: ${{ github.workspace }}/api.md
  REL_MARKDOWN_DIR: md
  ABS_MARKDOWN_DIR: ${{ github.workspace }}/md

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Tools
        run: |
          npm install -g jsdoc tui-jsdoc-template taffydb

      # Yes, two branches: main (stable) and scratch (scratch)
      # See https://github.com/nexushoratio/userscripts/issues/367
      - parallel:
        - name: Checkout (main)
          uses: actions/checkout@v7
          with:
            ref: main
            path: main

        - name: Checkout (scratch)
          uses: actions/checkout@v7
          with:
            ref: scratch
            path: scratch

      - name: Assemble Markdown
        run: |
          mkdir -p ${{ env.ABS_MARKDOWN_DIR }}/_layouts/
          cp -v "${GITHUB_REF_NAME}/pages/_layouts/"* ${{ env.ABS_MARKDOWN_DIR }}/_layouts
          cp -v "${GITHUB_REF_NAME}/"*.md ${{ env.ABS_MARKDOWN_DIR }}/
          for md in "${GITHUB_REF_NAME}/pages/"*.md; do
            echo >> ${{ env.ABS_MARKDOWN_DIR }}/README.md
            cat "${md}" >> ${{ env.ABS_MARKDOWN_DIR }}/README.md
          done

          cat << EOF > ${{ env.API_README_MD }}
          [userscript docs](..)

          ${{ github.workflow }} generation:${{ github.run_number }}

          Generated at: $(date -Imin) (via ${GITHUB_REF_NAME})
          EOF

      - parallel:
        # Jekyll runs as a Docker image and the output directories end up being
        # owned by root.  So we store them in a temp directory and later copy
        # the results over.
        - name: Jekyll
          uses: actions/jekyll-build-pages@v1
          with:
            source: ${{ env.REL_MARKDOWN_DIR }}
            destination: ${{ env.REL_JK }}

        # We currently build API from two branches, one as a WIP.
        - name: JSDoc (stable)
          run: |
            pushd main
            jsdoc -R ${{ env.API_README_MD }} -c .jsdoc.json -d ${{ env.ABS_JSDOC }}/stable -t $(npm root -g)/tui-jsdoc-template

        - name: JSDoc (scratch)
          run: |
            pushd scratch
            jsdoc -R ${{ env.API_README_MD }} -c .jsdoc.json -d ${{ env.ABS_JSDOC }}/scratch -t $(npm root -g)/tui-jsdoc-template

      - name: Merge document trees
        run: |
          pushd ${{ env.ABS_JK }}
          find -depth | cpio -pdmv ${{ env.ABS_JSDOC }}

      - name: Save
        uses: actions/upload-pages-artifact@v5
        with:
          path: ${{ env.ABS_JSDOC }}

  deploy:
    needs: build
    permissions:
      pages: write
      id-token: write
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    steps:
      - name: Pages
        uses: actions/deploy-pages@v5
